- hosts: k3s.nodes_config
  become: true
  vars_files:
    - variables.yaml

  tasks:
  - name: Set hostname
    hostname:
      name: "{{ NODES_HOSTNAME }}{{ groups['k3s.nodes_config'].index(inventory_hostname) | int + 1 }}"
  
  - name: Generate SSH key
    openssh_keypair:
      path: "~/.ssh/id_rsa"
      type: rsa
      size: 4096
      state: present
      force: no

  - name: Set up ENV
    apt:
      name: 
      - wget
      - curl
      - jq
      state: present
      update_cache: true

  - name: Set fixed IP
    ansible.builtin.script: ./res/set_ip.sh {{ STATIC_NODE_IP }} {{ ROUTER_IP }} {{ LOCAL_INTERFACE }} {{ groups['k3s.nodes_config'].index(inventory_hostname) }}

  - name: Get Github user SSH public keys
    shell: curl "https://api.github.com/users/{{ GITHUB_USER }}/keys" | jq -r '.[].key' >> ~/.ssh/authorized_keys

  - name: Disable SSH password
    shell: sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
