- hosts: k3s.dataend
  become: true
  vars_files:
    - variables.yaml

  tasks:
    - name: Install Zerotier
      shell: curl -s https://install.zerotier.com | sudo bash

    - name: Join Zerotier network
      shell: zerotier-cli join {{ ZEROTIER_NETWORK_ID }}

    - name: Wait to Zerotier Network join
      pause:
        seconds: 5

    - name: Allow Host on Zerotier
      script: ./res/allow_host.sh {{ ZEROTIER_NETWORK_ID }} {{ ZEROTIER_TOKEN }}

    - name: Set up ENV
      apt:
        name:
          - mariadb-server
        state: present
        update_cache: true

    - name: Ensure MySQL is enabled to run on startup
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Open DB
      shell: sed -i 's/bind-address            = 127.0.0.1/bind-address            = 0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
    
    - name: Ensure MySQL is enabled to run on startup
      service:
        name: mariadb
        state: restarted

    - name: "Install ansible python3 mysql dependency"
      apt:
        name: python3-mysqldb
        state: latest

    - name: Update MySQL root password for all root accounts
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ DB_PASS }}"
        login_user: root
        login_password: "{{ DB_PASS }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ DATAEND_HOSTNAME }}"
        - 127.0.0.1
        - ::1
        - localhost
        - 10.0.0.%
        - 192.168.192.%

    - name: Create k3s database
      mysql_db:
        name: "{{ DB_NAME }}"
        state: present
        login_user: root
        login_password: "{{ DB_PASS }}"
