- hosts: k3s.control_plane
  become: true
  vars_files:
    - variables.yaml

  tasks:
    - name: Install Zerotier
      shell: curl -s https://install.zerotier.com | sudo bash

    - name: Join Zerotier network
      shell: zerotier-cli join {{ ZEROTIER_NETWORK_ID }}

    - name: Wait to Zerotier Network join
      pause:
        seconds: 5

    - name: Allow Host on Zerotier
      script: ./res/allow_host.sh {{ ZEROTIER_NETWORK_ID }} {{ ZEROTIER_TOKEN }}

    - name: Deploy k3s
      shell: curl -sfL https://get.k3s.io | sh -s - server --datastore-endpoint="mysql://{{ DB_USER }}:{{ DB_PASS }}@tcp({{ DB_HOST }}:3306)/{{ DB_NAME }}"

    - name: Register a new value
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: K3S_TOKEN